### ISSUE TITLE
Sound + Outer city regions

### ISSUE THREAD

**Issue by brandesdavid** [FreiFahren/frontend#63]

**Comment by brandesdavid** [comment]
someone suggested us to also put in a sound like the blitzer app.
We should also focus a bit on the C ticket region, because many inspectors are waiting extra for people with no c tickets

**Comment by johan-t** [comment]
Is it possible to play sounds in web apps?

**Comment by brandesdavid** [comment]
> Is it possible to play sounds in web apps?

If it is possible for spotify then it is possible for us
